version: '3.3'

services:
  app:
    build: api
    volumes:
      - .:/app
    working_dir: /app/api
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    # command: bash -c "uvicorn api:app --host 0.0.0.0"
